proc sql ; 
create table CAMPAGNES_DATE as 
/* TOTAL PAR CAMPAGNE */
select C.*
	, '31DEC9999'D as DATE_TRAITEMENT format date9.
	, NB_DIFFUSES
	, COALESCE(ROUND(NB_DIFFUSES/NB_CONSEILLER, 0.1),0)  as CIBLES_PAR_ETP
	, COALESCE(ROUND((NB_VENTES_EFFECTUEES + NB_RDV_PRIS + NB_REFUS_CLIENTS + NB_REFUS_CONSEILLERS + NB_CIBLAGES_INAPPROPRIES) / NB_DIFFUSES , 0.001),0) AS TRAITES
	, COALESCE(ROUND(NB_VENTES_EFFECTUEES / NB_DIFFUSES , 0.001),0) AS VENTES_EFFECTUEES
	, COALESCE(ROUND(NB_RDV_PRIS / NB_DIFFUSES , 0.001),0) AS RDV_PRIS
	, COALESCE(ROUND(NB_REFUS_CLIENTS / NB_DIFFUSES , 0.001),0) AS REFUS_CLIENTS
	, COALESCE(ROUND(NB_REFUS_CONSEILLERS / NB_DIFFUSES , 0.001),0) AS REFUS_CONSEILLERS
	, COALESCE(ROUND(NB_CIBLAGES_INAPPROPRIES / NB_DIFFUSES , 0.001),0) AS CIBLAGES_INAPPROPRIES
	, COALESCE(ROUND(NB_NON_TRAITES / NB_DIFFUSES , 0.001),0) AS NON_TRAITES
	, COALESCE(ROUND(NB_MESSAGES_REPONDEURS / NB_DIFFUSES , 0.001),0) AS MESSAGES_REPONDEURS

FROM  Import_campagnes as C 
inner join /* DIFFUSION */ 
	( select ID_CAMPAGNE
	, libelle_campagne
	, COUNT(COMAX) AS NB_DIFFUSES
	, COUNT(DISTINCt(COEM)) as NB_CONSEILLER
	, SUM(TOP_VENTES_EFFECTUEES) AS NB_VENTES_EFFECTUEES
	, SUM(TOP_RDV_PRIS) AS NB_RDV_PRIS
	, SUM(TOP_REFUS_CLIENT) AS NB_REFUS_CLIENTS
	, SUM(TOP_REFUS_CONSEILLER) AS NB_REFUS_CONSEILLERS
	, SUM(TOP_CIBLAGE_INAPPROPRIE) AS NB_CIBLAGES_INAPPROPRIES
	, SUM(TOP_NON_TRAITE) AS NB_NON_TRAITES
	, SUM(TOP_MESSAGE_REPONDEUR) AS NB_MESSAGES_REPONDEURS

	from LISTE_DETAILS_CAMPAGNES 
	group by ID_CAMPAGNE, libelle_campagne) 
	as D on D.ID_CAMPAGNE= C.ID and D.libelle_campagne= C.libelle_campagne

/* TRAITEMENT CAMPAGNE PAR DATE  */ 
UNION ALL  

select C.*
	, T.DATE_TRAITEMENT 
	, T.NB_DIFFUSES
	, COALESCE(ROUND(T.NB_DIFFUSES/D.NB_CONSEILLER, 0.1),0)  as CIBLES_PAR_ETP
	, COALESCE(ROUND((T.NB_VENTES_EFFECTUEES + T.NB_RDV_PRIS + T.NB_REFUS_CLIENTS + T.NB_REFUS_CONSEILLERS + T.NB_CIBLAGES_INAPPROPRIES) / D.NB_DIFFUSES , 0.001),0) AS TRAITES
	, COALESCE(ROUND(T.NB_VENTES_EFFECTUEES / D.NB_DIFFUSES , 0.001),0) AS VENTES_EFFECTUEES
	, COALESCE(ROUND(T.NB_RDV_PRIS / D.NB_DIFFUSES , 0.001),0) AS RDV_PRIS
	, COALESCE(ROUND(T.NB_REFUS_CLIENTS / D.NB_DIFFUSES , 0.001),0) AS REFUS_CLIENTS
	, COALESCE(ROUND(T.NB_REFUS_CONSEILLERS / D.NB_DIFFUSES , 0.001),0) AS REFUS_CONSEILLERS
	, COALESCE(ROUND(T.NB_CIBLAGES_INAPPROPRIES / D.NB_DIFFUSES , 0.001),0) AS CIBLAGES_INAPPROPRIES
	, COALESCE(ROUND(T.NB_NON_TRAITES / D.NB_DIFFUSES , 0.001),0) AS NON_TRAITES
	, COALESCE(ROUND(T.NB_MESSAGES_REPONDEURS / D.NB_DIFFUSES , 0.001),0) AS MESSAGES_REPONDEURS

FROM  Import_campagnes as C 
INNER JOIN (
 select ID_CAMPAGNE
	, libelle_campagne
	, datepart(DATE_MODIF) as DATE_TRAITEMENT format date9.
	, COUNT(COMAX) AS NB_DIFFUSES
	, COUNT(DISTINCt(COEM)) as NB_CONSEILLER
	, SUM(TOP_VENTES_EFFECTUEES) AS NB_VENTES_EFFECTUEES
	, SUM(TOP_RDV_PRIS) AS NB_RDV_PRIS
	, SUM(TOP_REFUS_CLIENT) AS NB_REFUS_CLIENTS
	, SUM(TOP_REFUS_CONSEILLER) AS NB_REFUS_CONSEILLERS
	, SUM(TOP_CIBLAGE_INAPPROPRIE) AS NB_CIBLAGES_INAPPROPRIES
	, SUM(TOP_NON_TRAITE) AS NB_NON_TRAITES
	, SUM(TOP_MESSAGE_REPONDEUR) AS NB_MESSAGES_REPONDEURS

	from LISTE_DETAILS_CAMPAGNES 
	where DATE_MODIF ne .
	group by ID_CAMPAGNE, libelle_campagne,calculated  DATE_TRAITEMENT  ) 
	as T on T.ID_CAMPAGNE= C.ID and T.libelle_campagne= C.libelle_campagne
inner join /* DIFFUSION  */ 
	( select ID_CAMPAGNE
	, libelle_campagne
	, COUNT(COMAX) AS NB_DIFFUSES
	, COUNT(DISTINCt(COEM)) as NB_CONSEILLER
	, SUM(TOP_VENTES_EFFECTUEES) AS NB_VENTES_EFFECTUEES
	, SUM(TOP_RDV_PRIS) AS NB_RDV_PRIS
	, SUM(TOP_REFUS_CLIENT) AS NB_REFUS_CLIENTS
	, SUM(TOP_REFUS_CONSEILLER) AS NB_REFUS_CONSEILLERS
	, SUM(TOP_CIBLAGE_INAPPROPRIE) AS NB_CIBLAGES_INAPPROPRIES
	, SUM(TOP_NON_TRAITE) AS NB_NON_TRAITES
	, SUM(TOP_MESSAGE_REPONDEUR) AS NB_MESSAGES_REPONDEURS
	from LISTE_DETAILS_CAMPAGNES 
	group by ID_CAMPAGNE, libelle_campagne) as D on D.ID_CAMPAGNE= C.ID and D.libelle_campagne= C.libelle_campagne

/* TRAITEMENT CAMPAGNE PAR DATE  */ 
OUTER UNION /*ALL*/ CORR
SELECT * 
from CAMPAGNES_TRAITEMENT ( where = (TYPE_ACTION= 'TOTAL')) ; 
;
 quit; 
